### ISSUE TITLE
CanFrame isExtended not working

### ISSUE THREAD

**Issue by frot** [pschichtel/JavaCAN#28]
The method CanFrame.isExtended() checks for EFF_FLAG in already masked id received from CanFrame.getId()

Should probably use getRawId instead.

**Comment by frot** [comment]
Same fault in isError and isRemoteTransmissionRequest ?

**Comment by pschichtel** [comment]
Whoops, will fix that

**Comment by pschichtel** [comment]
@frot Do you need this backported to 2.x?

**Comment by frot** [comment]
No need to backport. I have a work-around. Thanks!
