### ISSUE TITLE
Examples or API documentation

### ISSUE THREAD

**Issue by DoctorZIP** [pschichtel/JavaCAN#32]
Hi,
First of all, I want to thank you for a great job. It's really easy to kickstart and check if the system works in a first approach but, it is a lack of examples of descriptions on more complex things like filters and non-blocking API. Could you please provide such information or point out where it could be found?
Thank you!

**Comment by pschichtel** [comment]
The unit tests provide some usage examples for various things. The general API design of the core module is very close to any other Channel implementation and epoll module is very close to Java's Selector API (actually, in 2.x it implements the Selector API, but that implementation is not completely correct). Options are named exactly like they are in SocketCAN. I intentionally tried to stay as close as possible to existing and familiar APIs, so users can transfer existing knowledge from elsewhere and I can avoid writing lots of documentation :smile: . I do see your point though.

If you have specific things you need, please mention them and I'll see if I can write up some documentation and/or an additional test. Do understand though, they I'll only be writing documentation for version 3.0 and not for the 2.x branch.

**Comment by DoctorZIP** [comment]
Okay. Thank you! When do you plan to release version 3?

**Comment by pschichtel** [comment]
Actually I just did. For some reason the deployment to maven central did not work, looking into that later today...

**Comment by pschichtel** [comment]
@DoctorZIP fixed it 3.0.1 is now available from maven central

**Comment by DoctorZIP** [comment]
> @DoctorZIP fixed it 3.0.1 is now available from maven central

Looks like no JARs are included https://repo.maven.apache.org/maven2/tel/schich/javacan/3.0.1/

**Comment by pschichtel** [comment]
the javacan artifact itself is now just an aggregator. javacan-core and javacan-epoll are what you need now:

* https://repo.maven.apache.org/maven2/tel/schich/javacan-core/3.0.1/
* https://repo.maven.apache.org/maven2/tel/schich/javacan-epoll/3.0.1/
