### ISSUE TITLE
Published artifacts  (maven central) does not include jar file

### ISSUE THREAD

**Issue by adparts** [pschichtel/JavaCAN#58]
![image](https://github.com/pschichtel/JavaCAN/assets/50626839/ac58194d-c762-4e35-963d-974ec23713aa)

Using this project in a maven fails the download:

Failed to execute goal on project javacan: Could not resolve dependencies for project xxxxxx: **tel.schich:javacan:jar:3.4.0 was not found in https://repo.maven.apache.org/maven2** during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by pschichtel** [comment]
JavaCAN without -core or -epoll are not being published anymore since the gradle migration a few days ago. The javacan artifact has been a pom-only artifact for years now, since the epoll module exists.
