### ISSUE TITLE
JSON Serialization of Frames

### ISSUE THREAD

**Issue by ztword** [pschichtel/JavaCAN#62]
Hi， Brother ！！！ How do I parse CAN message ? How does the message go to JSON ？

**Comment by pschichtel** [comment]
Are you interested in serialization from/to json? JavaCAN doesn't come with any mapping logic and it's objects probably won't work well with reflection-based mapping. You'd have to write your own custom mapping classes.

I wonder if the new structure I used for j1939 works for reflection based mappers, maybe I can provide something similar for raw frames.

**Comment by pschichtel** [comment]
I'm closing this due to a lack of feedback.
